# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install --upgrade pytube --quiet

# Step 1: Install yt-dlp
!pip install yt-dlp --quiet

# Step 2: Import necessary modules
import os
from google.colab import files

# Step 3: Define the function to download a video
def download_youtube_video():
    # Get the video URL from the user
    video_url = input("Enter the YouTube video URL: ")

    try:
        # Set up the output format
        output_path = "/content"
        output_template = os.path.join(output_path, "%(title)s.%(ext)s")

        # Use yt-dlp to download the video
        print("\nDownloading the video...")
        !yt-dlp -o "{output_template}" {video_url}

        # Find the downloaded file
        for file in os.listdir(output_path):
            if file.endswith(".mp4"):
                downloaded_file = os.path.join(output_path, file)
                break

        print(f"\nDownload complete! Video saved as: {downloaded_file}")

        # Offer the user to download the file to their local machine
        files.download(downloaded_file)

    except Exception as e:
        print(f"An error occurred: {e}")

# Run the downloader
download_youtube_video()